### ISSUE TITLE
java.lang.IllegalStateException: Couldn't match exception header

### ISSUE THREAD

**Issue by denysz** [square/spoon#125]
```
java.lang.IllegalStateException: Couldn't match exception header.
    at com.squareup.spoon.misc.StackTrace.acceptTrace(StackTrace.java:84)
    at com.squareup.spoon.misc.StackTrace.from(StackTrace.java:76)
    at com.squareup.spoon.DeviceTestResult$Builder.markTestAsFailed(DeviceTestResult.java:82)
    at com.squareup.spoon.SpoonTestRunListener.testFailed(SpoonTestRunListener.java:40)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.reportResult(InstrumentationResultParser.java:457)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.parseStatusCode(InstrumentationResultParser.java:411)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.parse(InstrumentationResultParser.java:272)
    at com.android.ddmlib.testrunner.InstrumentationResultParser.processNewLines(InstrumentationResultParser.java:243)
    at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:99)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:419)
    at com.android.ddmlib.Device.executeShellCommand(Device.java:444)
    at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:211)
    at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:196)
    at com.squareup.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:188)
    at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:111)
    at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:78)
    at com.squareup.spoon.SpoonRunner.main(SpoonRunner.java:376)
```

**Comment by edenman** [comment]
Too old, closing this out.  @denysz, re-open if you're still having problems.
