### ISSUE TITLE
java.lang.RuntimeException: Unable to capture screenshot

### ISSUE THREAD

**Issue by denysz** [square/spoon#148]
java.lang.RuntimeException: Unable to capture screenshot.
    at com.squareup.spoon.Spoon.screenshot(Spoon.java:54)
    at com.qa.testcase.android.Test09Settings.testSettings(Test09Settings.java:111)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
    at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
    at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
    at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
Caused by: java.lang.IllegalAccessException: Unable to create output dir: /data/system/app_spoon-screenshots

Line Test09Settings.java:111 is below:
Spoon.screenshot(solo.getCurrentActivity(), "before_logout");

**Comment by jabKnowsNothing** [comment]
I run into this issue when I try to take a screenshot of an activity with the drawer open.  I get a similar stack trace to that posted above.

Using "android.support.v4.widget.DrawerLayout"

**Comment by edenman** [comment]
1.1.4 now lets you specify the test class/method names in Spoon.screenshot, so you can do this in your setup/tearDown.
