### ISSUE TITLE
com.android.ddmlib.AdbCommandRejectedException

### ISSUE THREAD

**Issue by mgmanikandan87** [square/spoon#153]
com.android.ddmlib.AdbCommandRejectedException: device not found
    at com.android.ddmlib.AdbHelper.setDevice(AdbHelper.java:752)
    at com.android.ddmlib.SyncService.openSync(SyncService.java:168)
    at com.android.ddmlib.Device.getSyncService(Device.java:409)
    at com.squareup.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:215)
    at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:111)
    at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:78)
    at com.squareup.spoon.SpoonRunner.main(SpoonRunner.java:376)

I have around 25 test cases , every run after 5th or 6th test case i got above error and spoon get stopped.

Advance thanks for help.

**Comment by edenman** [comment]
I think this may be fixed by #245, closing.  Re-open if you still have issues on 1.1.5 (once it's released)
