### ISSUE TITLE
Option to ignore any device that failed to run all the tests.

### ISSUE THREAD

**Issue by yogurtearl** [square/spoon#192]
Similar to #191 , sometimes adb has a hickup that causes it to not be get the results from one of the devices. 

It would be nice to have an option to ignore these failures.

```
Test failed to run to completion. Reason: 'Test run failed to complete. Expected 72 tests, received 46'. Check device logcat for details
```

**Comment by ouguangqian** [comment]
I have the same ,but sometimes it's OK! 
Test failed to run to completion. Reason: 'Test run failed to complete. Expected 20 tests, received 14'. Check device logcat for details
Tests on ASTEROID - 4.3 failed: Test run failed to complete. Expected 20 tests, received 14


* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:connectedDebugAndroidTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)

**Comment by kirillzh** [comment]
Having same problem, was it resolved?

**Comment by omelkova** [comment]
@JakeWharton
I faced the same problem with latest spoon version. Is there any understanding what can cause this error? 
I can send additional info about the test run if it may help to investigate 
Thank you very much for this useful library!

**Comment by JD-90** [comment]
@omelkova Hey, have you been able to identify this issue's root cause? It's failing most of my tests runs for no apparent reason.

**Comment by raviranjanchaudhari-tudip** [comment]
did this issue is resolved?

**Comment by raviranjanchaudhari-tudip** [comment]
Does anyone have a solution on the same?
