### ISSUE TITLE
Could not find application package when running test runner

### ISSUE THREAD

**Issue by ancientmethods** [square/spoon#224]
Hello. I'm not sure why the application package is not recognised. Any ideas?

Exception in thread "main" java.lang.NullPointerException: Could not find application package.
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:
226)
        at com.squareup.spoon.SpoonInstrumentationInfo.parseFromFile(SpoonInstru
mentationInfo.java:78)
        at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:112)
        at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:92)
        at com.squareup.spoon.SpoonRunner.main(SpoonRunner.java:453)

**Comment by sayoojvalsan-demandmedia** [comment]
How did u solve this ? I see the same issue?

**Comment by yashasvimakin** [comment]
@sayoojvalsan-demandmedia  is this issue Solved??

**Comment by rajat-bb** [comment]
In my case, I was specifying the wrong apk in `--test-apk` param. It got resolved when the specified the actual test apk there.
