### ISSUE TITLE
Support for JUnit4 tests that don't extend InstrumentationTestCase

### ISSUE THREAD

**Issue by chrisjenx** [square/spoon#232]
Unless this is already open, seem's using JUnit4 + Espresso is causing issues.

```
ava.lang.RuntimeException: Unable to capture screenshot.
at com.squareup.spoon.Spoon.screenshot(Spoon.java:57)
at com.justyoyo.test.StartingEspressoTest.testRegister(StartingEspressoTest.java:38)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
at com.justyoyo.test.utils.ActivityRule$1.evaluate(ActivityRule.java:99)
at org.junit.rules.RunRules.evaluate(RunRules.java:18)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:24)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:270)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
Caused by: java.lang.IllegalArgumentException: Could not find test class!
at com.squareup.spoon.Spoon.findTestClassTraceElement(Spoon.java:136)
at com.squareup.spoon.Spoon.obtainScreenshotDirectory(Spoon.java:118)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:50)
```

For:
```java
@RunWith(AndroidJUnit4.class)
public class StartingEspressoTest {

    @Rule
    public final ActivityRule<StartingActivity> main = new ActivityRule<>(StartingActivity.class);

    private StartingActivity mActivity;

    @Before
    public void setUp() throws Exception {
        mActivity = main.get();
    }

    @Test
    public void testRegister() throws Exception {
        Spoon.screenshot(mActivity, "starting_state");
        // Go to register screen
        onView(withContentDescription("Register with Email")).perform(click());
        Spoon.screenshot(mActivity, "register_state");
    }
}
```
I'm guessing because the `AndroidJUnitRunner` does not extend from `InstrumentationTestCase`. 
I have seen other issues discussing opening up the method to allow passing in of Instrumentation, I guess this would make more sense ultimately.

**Comment by edenman** [comment]
Known issue but doesn't look like it's tracked.  Thanks!  Related to #220
