### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: SDK path not specified

### ISSUE THREAD

**Issue by okhit007** [square/spoon#275]
I am runtime ,Prompt the error,who can help me ,thanks~~

Exception in thread "main" java.lang.NullPointerException: SDK path not specified.
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
        at com.squareup.spoon.SpoonRunner$Builder.setAndroidSdk(SpoonRunner.java:251)
        at com.squareup.spoon.SpoonRunner.main(SpoonRunner.java:490)

**Comment by JakeWharton** [comment]
Specify the SDK folder with `--sdk` command-line argument or by setting the `ANDROID_HOME` environment variable.
