### ISSUE TITLE
Can't create screenshot dir on CI emulator

### ISSUE THREAD

**Issue by sregg** [square/spoon#283]
I'm trying to setup a CircleCI and Spoon is failing because it can't create the screenshot directory on the sdcard: 

```
java.lang.RuntimeException: Unable to capture screenshot.
at com.squareup.spoon.Spoon.screenshot(Spoon.java:80)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:53)
at com.sregg.android.tv.spotify.ui.activity.MainActivityTest.shouldOpen(MainActivityTest.java:37)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at com.sregg.android.tv.spotify.testUtils.rule.FailureScreenshotRule$1.evaluate(FailureScreenshotRule.java:27)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:228)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
Caused by: java.lang.IllegalAccessException: Unable to create output dir: /storage/sdcard/app_spoon-screenshots
at com.squareup.spoon.Spoon.createDir(Spoon.java:180)
at com.squareup.spoon.Spoon.createDir(Spoon.java:177)
at com.squareup.spoon.Spoon.createDir(Spoon.java:177)
at com.squareup.spoon.Spoon.obtainScreenshotDirectory(Spoon.java:151)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:72)
```

You can see the build here: https://circleci.com/gh/sregg/spotify-tv/21

I do have the WRITE_EXTERNAL_STORAGE permission in the main manifest.

Thanks for your help.

**Comment by edenman** [comment]
So I dug around in this code and I can't tell from the CircleCI output what's going wrong here.  Some possibilities:

- Maybe it's something wonky on the permissions of `/storage/sdcard` (check which user owns this dir)?  
- Or maybe you misspelled the external storage permission? Needs to be `android.permission.WRITE_EXTERNAL_STORAGE` exactly.  Does the test pass when you run it locally?  

Regardless, maybe add some debugging output to your CircleCI build steps to try and track down why the directory can't be created?  something like (not actually tested for accurate syntax) `adb shell ls -l /storage/`

**Comment by sregg** [comment]
The tests pass perfectly when removing the Spoon.screenshot() statement.
I tried `adb shell ls -l /storage/` and everything was fine, permissions etc...

Is there a way to write the screenshots in the internal memory instead of the external one?
I see in the code that if the SDK is >= 21, it uses the external by default. Is there a way to override that behaviour?

**Comment by sregg** [comment]
I just tried to create the directory manually through adb shell:

>root@generic:/ # mkdir /storage/sdcard/app_spoon-screenshots                   
>mkdir failed for /storage/sdcard/app_spoon-screenshots, Read-only file system

...

Looks like the emulator's sdcard is read only. How is it working for your guys?

**Comment by edenman** [comment]
@sregg we don't use CircleCI to run our Spoon tests (we just have some devices hooked up to a test machine in the office).  Maybe there's a configuration value to make the sdcard on CircleCI emulators writeable?  Regardless, this doesn't seem like a Spoon problem so I'm going to close this issue.

**Comment by sregg** [comment]
Apparently, you need to create a sdcard image file using `mksdcard` in order to have a writable sdcard.

`mksdcard -l e 512M mysdcard.img`

and then use it in the emulator command

`emulator -avd circleci-android22 -no-audio -no-window -sdcard mysdcard.img`
