### ISSUE TITLE
No logcat header processed when using 1.2.1-jar

### ISSUE THREAD

**Issue by xiaoshun0512** [square/spoon#303]
when excuting cases in jekins ,  i get the following exception from the output
Exception in thread "Thread-1" java.lang.IllegalStateException: No logcat header processed yet, failed to parse line: --------- beginning of /dev/log/system
	at com.android.ddmlib.logcat.LogCatMessageParser.processLogLines(LogCatMessageParser.java:123)
	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processLogLines(LogCatReceiverTask.java:112)
	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processNewLines(LogCatReceiverTask.java:107)
	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:353)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
	at com.android.ddmlib.logcat.LogCatReceiverTask.run(LogCatReceiverTask.java:75)
	at java.lang.Thread.run(Thread.java:745)

and my test-result-logcat is empty
![image](https://cloud.githubusercontent.com/assets/8308075/11334519/8a73a456-9210-11e5-853e-d57ffa674a93.png)

**Comment by JakeWharton** [comment]
Dupe #302. Update your Android SDK?
