### ISSUE TITLE
No logcat header processed yet, failed to parse line:

### ISSUE THREAD

**Issue by atobulredy** [square/spoon#305]
Exception in thread "Thread-1" java.lang.IllegalStateException: No logcat header processed yet, failed to parse line: --------- beginning of /dev/log/system
        at com.android.ddmlib.logcat.LogCatMessageParser.processLogLines(LogCatMessageParser.java:123)
        at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processLogLines(LogCatReceiverTask.java:112)
        at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processNewLines(LogCatReceiverTask.java:107)
        at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:353)
        at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
        at com.android.ddmlib.logcat.LogCatReceiverTask.run(LogCatReceiverTask.java:75)
        at java.lang.Thread.run(Unknown Source)

Not able to capture logs.

Please help

**Comment by edenman** [comment]
@atobulredy dup of #302
