### ISSUE TITLE
Error when running Spoon on multiple devices

### ISSUE THREAD

**Issue by rafaelaazevedo** [square/spoon#316]
I am getting this error when running Spoon on multiple devices, on the previous version 1.2.1, but on 1.3.1 I've started to get this error:

2016-02-02 17:27:36 [SDR.runInNewProcess] Process.waitFor() finished for [OUGRYMJ7] with exitCode 1
java.io.FileNotFoundException: /app/build/spoon-output/DebugAndroidTest/work/OUGRYMJ7/result.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.squareup.spoon.SpoonDeviceRunner.runInNewProcess(SpoonDeviceRunner.java:140)
	at com.squareup.spoon.SpoonRunner$1.run(SpoonRunner.java:171)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-02-02 17:27:36 [SDR.runInNewProcess] Process.waitFor() finished for [WAWJM0X9] with exitCode 1
java.io.FileNotFoundException: /app/build/spoon-output/DebugAndroidTest/work/WAWJM0X9/result.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.squareup.spoon.SpoonDeviceRunner.runInNewProcess(SpoonDeviceRunner.java:140)
	at com.squareup.spoon.SpoonRunner$1.run(SpoonRunner.java:171)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Someone had the same problem ?
If I run just one tablet I don't have the problem.

**Comment by rafaelaazevedo** [comment]
Ah I found another already opened bug https://github.com/square/spoon/issues/177
