### ISSUE TITLE
Jenkins build fails due to: INSTALL_FAILED_UPDATE_INCOMPATIBLE

### ISSUE THREAD

**Issue by Slythefly** [square/spoon#342]
**com.stanfy.spoon:spoon-gradle-plugin:1.1.0**

Running Espresso UI tests with Spoon on my local machine works as expected (running command: `./gradlew clean spoonSeDebugAndroidTest`), but if I try to run from a Jenkins server (with the Gradle plugin) it fails with the following output:

10:16:37 D/app-se-debug.apk: Uploading app-se-debug.apk onto device '1215fc483bd31204'
10:16:37 D/Device: Uploading file onto device '1215fc483bd31204'
10:16:49 D/app-se-debug-androidTest-unaligned.apk: Uploading app-se-debug-androidTest-unaligned.apk onto device '1215fc483bd31204'
10:16:49 D/Device: Uploading file onto device '1215fc483bd31204'
2016-05-18 10:16:50 [SDR.run] InstallException while install test apk on device [1215fc483bd31204]
com.android.ddmlib.InstallException: INSTALL_FAILED_UPDATE_INCOMPATIBLE
	at com.android.ddmlib.Device.installRemotePackage(Device.java:976)
	at com.android.ddmlib.Device.installPackage(Device.java:883)
	at com.squareup.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:198)
	at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:164)
	at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:123)
	at com.squareup.spoon.SpoonRunner$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at com.stanfy.spoon.gradle.SpoonRunTask.runSpoon(SpoonRunTask.groovy:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227

So how come I only see this in Jenkins? any ideas?

**Comment by bagintz** [comment]
@Slythefly I have seen this when we have an old version of the app on the device.  We ended up making sure to uninstall the app and the test app as part of our process.

**Comment by Slythefly** [comment]
@bagintz Thanks, seems to be the same issue here. The solution is to uninstall it with adb, i.e.
`adb uninstall <package name>`. Uninstalling from the phone was not enough for some reason.

**Comment by mbmc** [comment]
If you're facing the problem, make sure to remove the regular apk, and the instrumentation apk.
Recently, seems that we can't install directly a debug apk if there's already one signed with a different debug key.

**Comment by eygraber** [comment]
I've seen this even after making sure the APK was uninstalled. The trick was the [answer here](http://stackoverflow.com/questions/28949722/android-tests-fail-on-travis-with-shellcommandunresponsiveexception) (increase the adb timeout with the `ADB_INSTALL_TIMEOUT` environment variable).
