### ISSUE TITLE
Build fails when running with --coverage true

### ISSUE THREAD

**Issue by hewhomustnotbenamed** [square/spoon#346]
Whenever I try to run with --coverage true as parameter the build fails saying file not found.

Here is the command that I am using to run the tests

> java -jar spoon-runner-1.5.4-jar-with-dependencies.jar --apk core-myapp-debug-androidTest-unaligned.apk --test-apk core-myapp-debug-androidTest-unaligned.apk --coverage true --shard

```
2016-06-13 17:48:58 [SR.runTests] Executing instrumentation suite on 1 device(s).
Exception in thread "Thread-1" java.lang.IllegalStateException: No logcat header processed yet, failed to parse line: --------- beginning of crash
	at com.android.ddmlib.logcat.LogCatMessageParser.processLogLines(LogCatMessageParser.java:123)
	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processLogLines(LogCatReceiverTask.java:112)
	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processNewLines(LogCatReceiverTask.java:107)
	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:353)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
	at com.android.ddmlib.logcat.LogCatReceiverTask.run(LogCatReceiverTask.java:75)
	at java.lang.Thread.run(Thread.java:745)
2016-06-13 17:49:21 [SDR.handleFiles] Found class name dirs: []
Exception in thread "main" java.lang.RuntimeException: error while merging coverage files
	at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:224)
	at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:124)
	at com.squareup.spoon.SpoonRunner.main(SpoonRunner.java:648)
Caused by: java.io.FileNotFoundException: spoon-output/coverage/192_168_70_102_5555/coverage.ec (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:71)
	at com.squareup.spoon.SpoonCoverageMerger.mergeCoverageFiles(SpoonCoverageMerger.java:28)
	at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:221)
	... 2 more
```

**Comment by edenman** [comment]
@jainsahab any ideas?

**Comment by jainsahab** [comment]
I am aware of this issue, this happens on physical device while pulling files from device because coverage files are being generated into app folder and on physical device it's not allowed to access the app directory. I will soon address this issue.

**Comment by edenman** [comment]
Just released 1.5.5, should be live soon.

**Comment by hewhomustnotbenamed** [comment]
Thanks @jainsahab. Its working for me too!!

**Comment by bagintz** [comment]
I am getting this still with Emulator API 18 on 1.5.6
