### ISSUE TITLE
Still getting "error while merging coverage files" (1.6.2)

### ISSUE THREAD

**Issue by bagintz** [square/spoon#368]
With 1.6.2 I am still getting the file not found issue.  I am not sure exactly what it should be doing as I have never had the coverage work for me :(.  Any ideas?

**Comment by bagintz** [comment]
Ok, stupid mistake on my part, but it might be nice to document somewhere:

You must make sure you still have this in your app build.gradle:

buildTypes {
        debug {
             testCoverageEnabled = true
        }
    }

**Comment by bagintz** [comment]
Quick question in case anyone sees it here, I got the coverage working, does this include unit tests, or just UI/IT tests?

**Comment by jainsahab** [comment]
HI @bagintz , this will include only IT tests, not the unit tests.

**Comment by Yurii-Laguta** [comment]
Having same problem on version 1.7.1 when forth devices is connected. Tried to replace device with another one had same issue again.
`Caused by: java.io.FileNotFoundException: /Users/teamcitybuild/buildAgent_tc10/work/f6c10a89e556655/myproject/my/package/app/build/spoon/debug/coverage/CVH7N15B14000280/coverage.ec (No such file or directory)
[:app:testDebugUnitTest] 	at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:71)
[:app:testDebugUnitTest] 	at com.squareup.spoon.SpoonCoverageMerger.mergeCoverageFiles(SpoonCoverageMerger.java:28)`

**Comment by jaredsburrows** [comment]
This maybe related to: https://issuetracker.google.com/37008153 and https://issuetracker.google.com/37019591.

**Comment by stanroy** [comment]
Having the same problem, even with 
```testCoverageEnabled true```
