### ISSUE TITLE
Travis InstallException

### ISSUE THREAD

**Issue by eygraber** [square/spoon#378]
When I run `./gradlew spoonDebug -PdisablePreDex --continue --stacktrace` on Travis, I get the following error:

```
:app:spoonDebugAndroidTest
2016-08-26 17:58:41 [SR.runTests] Executing instrumentation suite on 1 device(s).
2016-08-26 18:06:01 [SDR.run] InstallException while install test apk on device [emulator-5554]
com.android.ddmlib.InstallException
	at com.android.ddmlib.Device.installRemotePackage(Device.java:983)
	at com.android.ddmlib.Device.installPackage(Device.java:883)
	at com.squareup.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:204)
	at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:167)
	at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:126)
	at com.squareup.spoon.SpoonRunner$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at com.stanfy.spoon.gradle.SpoonRunTask.runSpoon(SpoonRunTask.groovy:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    ...
```

I make sure to uninstall both my app and the test app from the emulator before running this. It happens sporadically, and never has happened when I run it locally. I use the `sys-img-armeabi-v7a-google_apis-21` emulator image, with build tools 24.0.1 and SDK 24 as the compile SDK.

**Comment by eygraber** [comment]
Closing as dupe https://github.com/square/spoon/issues/342
