### ISSUE TITLE
Spoon screenshot crash for Marshmallow Device 

### ISSUE THREAD

**Issue by Kiran89kumar** [square/spoon#379]
Spoon is getting crashed while running connectedDebugAndroidTest.

_Crash_ Log: java.lang.RuntimeException: Unable to capture screenshot.
Caused by: java.io.FileNotFoundException: /storage/emulated/0/app_spoon-screenshots/com.xxx.xyz.MainActivityTest/demoTest/1472536152119_Capture.png: open failed: EACCES (Permission denied)
at libcore.io.IoBridge.open(IoBridge.java:452)
at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
at com.squareup.spoon.Spoon.takeScreenshot(Spoon.java:123)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:85)
... 17 more
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
at libcore.io.IoBridge.open(IoBridge.java:438)
... 21 more_

Same thing will work fine after running spoon.

**Comment by AAverin** [comment]
Same.
Spoon should correctly as for permission when running on 6.0+ devices

**Comment by tir38** [comment]
Is this not working for you?

module-level build.gradle:
```
spoon {
    // To grant permissions to Android M >= devices */
    grantAllPermissions = true
}
```

Mine screenshots works fine on 6.0.1

**Comment by AAverin** [comment]
Didn't know about this one, will try, thanks
