### ISSUE TITLE
Could not find application package

### ISSUE THREAD

**Issue by sayoojvalsan-demandmedia** [square/spoon#381]
I followed the examples

`java -jar ~/Downloads/spoon-runner-1.6.4-jar-with-dependencies.jar  --apk app/build/outputs/apk/app-xxx.apk --test-apk app/build/outputs/apk/xxx-unaligned.apk`

Exception in thread "main" java.lang.NullPointerException: Could not find application package.
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
    at com.squareup.spoon.SpoonInstrumentationInfo.parseFromFile(SpoonInstrumentationInfo.java:88)
    at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:117)
    at com.squareup.spoon.SpoonRunner.main(SpoonRunner.java:694)

Thoughts ?

**Comment by JakeWharton** [comment]
Your test APK is missing its application package declaration. Are you sure
those are the right APKs?

**Comment by sayoojvalsan-demandmedia** [comment]
I checked again. Yes they are the right apks I got from doing assembleQADebug.
We are using QA flavor.

**Comment by sayoojvalsan-demandmedia** [comment]
[build.gradle.txt](https://github.com/square/spoon/files/450599/build.gradle.txt)

Attached build.gradle

**Comment by JakeWharton** [comment]
Without the APKs themselves it will be very hard for us to be able to
figure out what's going wrong.

**Comment by yashasvimakin** [comment]
@JakeWharton i am also facing the same issue please help.

**Comment by JakeWharton** [comment]
No action to take without an example test APK that exhibits this behavior.
