### ISSUE TITLE
RuntimeException: error while merging coverage files

### ISSUE THREAD

**Issue by caipivara** [square/spoon#403]
This is still happening: https://github.com/square/spoon/issues/346

Tested with:
- Nexus 5x with Android `6.0.1`
- Circle ci emulator: `circleci-android22`
- android gradle tools `2.2.2`
- spoon-client `1.7.0`

Project build: https://circleci.com/gh/MakinGiants/banjen/12

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:spoonDebugAndroidTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: error while merging coverage files
        at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:232)
        at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:132)
        at com.squareup.spoon.SpoonRunner$run.call(Unknown Source)
        at com.stanfy.spoon.gradle.SpoonRunTask.runSpoon(SpoonRunTask.groovy:191)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:136)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:129)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:118)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
Caused by: java.io.FileNotFoundException: /Users/danielgomez/projects/banjen/app/build/spoon/debug/coverage/00c572fedbd7a1ca/coverage.ec (No such file or directory)
        at org.jacoco.core.tools.ExecFileLoader.load(ExecFileLoader.java:71)
        at com.squareup.spoon.SpoonCoverageMerger.mergeCoverageFiles(SpoonCoverageMerger.java:28)
        at com.squareup.spoon.SpoonRunner.runTests(SpoonRunner.java:229)
        ... 25 more
```

**Comment by edenman** [comment]
@jainsahab any ideas?

**Comment by spirosoik** [comment]
I have the same problem

**Comment by jainsahab** [comment]
Hi all, By looking at the problem, it seems like `coverage.ec` file has not generated. and AFAIK it is possible because of two reasons.

1.)  the build(APK) under test, is not **emma instrumented** build.

2.)  the instrumentation process on the devices is crashed somehow and spoon process didn't recognize that crash. Hence spoon still tries to pull and merge the coverage file which couldn't generate because of the crash. I have also faced this issue on the random basis. It happens very rarely.

If you are always getting this issue, most probably the first reason is causing this failure and can be resolved using this configuration.

`
    buildTypes {
        debug {
            testCoverageEnabled = true
        }
    }
`

But yeah, instead of throwing a very generic error. We can mention this solution as part of the exception. @edenman let me know your views on this.

**Comment by edenman** [comment]
@jainsahab nice.  looks like @caipivara's [PR](https://github.com/MakinGiants/banjen/pull/15/files) doesn't set that flag.  I'd be in favor of adding to the exception message to make this requirement more clear.  Maybe `Error while merging coverage files.  Did you set the "testCoverageEnabled" flag in your build.gradle?`

**Comment by jainsahab** [comment]
Thanks @edenman , a PR is on its way.

**Comment by caipivara** [comment]
@jainsahab I tried adding the flag but now I get another error, looks like its a bug in android gralde plugin.

https://circleci.com/gh/MakinGiants/banjen/13

This is the error:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;
at com.makingiants.android.banjotuner.EarActivity.$jacocoInit(EarActivity.kt)
at com.makingiants.android.banjotuner.EarActivity.<init>(EarActivity.kt)
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.Class.newInstance(Class.java:1606)
at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5257)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_b0d6a23.Offline" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.makingiants.android.banjotuner.test-1/base.apk", zip file "/data/app/com.makingiants.android.banjotuner-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 16 more
Suppressed: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_b0d6a23.Offline
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 17 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

do you know on which versions it is working?

**Comment by jainsahab** [comment]
@caipivara Yup, it looks like a bug with the android gradle plugin itself as per this [stackover answer](http://stackoverflow.com/a/39195755/2911348).
there are some possible workarounds also mentioned in that answer, they may help you.
FYI: my configurations are
Gradle => 2.13
Android Gradle Plugin => 2.1.0
and jacoco version in the given code snippet
```
apply plugin: 'jacoco'
jacoco {
    toolVersion = "0.7.4.201502262128"
}
```

**Comment by caipivara** [comment]
@jainsahab it works with that setup :) thanks and sorry for the false alarm.

**Comment by jayshildave** [comment]
Hi All,

I have similar error. 
The issue is as below and somewhat related to above thread.

Spoon Gradle Plugin Dependency: com.stanfy.spoon:spoon-gradle-plugin:1.2.2
Client version:
androidTestCompile 'com.squareup.spoon:spoon-client:1.7.1'

Now when i am running the app i get a crash 
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_b0d6a23.Offline"

Android Gradle Tools Version is
tools.build:gradle:2.3.0
Build tool version is 
buildToolsVersion "25.0.2"

For my debug build type is 
debug {
            testCoverageEnabled true
        }

If i set this value as false it works without a problem. I am guessing there is some issue with the jacoco version in gradle tools 2.3.0 and spoons gradle 1.2.2

I am not using spoons coverage value because i was getting issue of error merging code coverage. I am using gradle task

gradle createDebugCoverageReport for the same.

Note: without adding spoon this works fine. As soon as i add spoon the conflict occurs.
Are we aware which is the jacoco version being referred by spoons gradle 1.2.2?

**Comment by AnshumanRohella** [comment]
@jainsahab You mentioned EMMA instrumented. Do you have more info about using EMMA with gradle? The last time I tried to use EMMA, it required build.xml which was generated by android updtate <project> command which has been removed. I tried using EMMA but it requires coverage.em file too. Any info on EMMA and gradle use ?

**Comment by TheOddPanda** [comment]
This is actually still a thing (two years later...). We experience the same issue even though it's two years later. How can one fix it? We set the testCoverageEnabled-Flag already to true but we still get that issue.

**Comment by cody1024d** [comment]
I am getting similar issues when generating coverage.ec files into the External Storage.

I am testing on an emulator, btw.

To verify, I've even directly used ADB to run tests, and try to generate coverage like this:

```
adb shell am instrument -w -r -e coverage true -e coverageFile /sdcard/coverage.ec -e debug false -e class com.sample.test.FooTest#FooBarTest com.sample.test/androidx.test.runner.AndroidJUnitRunner
```

Running this command results in tests succeeding, but the following error:

`Error: Failed to generate Emma/JaCoCo coverage.`

Need to debug further to see why some times the SDCard is not able to be accessed.
