### ISSUE TITLE
Unable to capture screenshot. Caused by: java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by sika78** [square/spoon#446]
Hi guys,

I'm using:
classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.2.2'
androidTestCompile 'com.squareup.spoon:spoon-client:1.6.4'
and I keep getting this crash (3 out 5 times) .

This is how I capture screenshots;
Spoon.screenshot(solo.getCurrentActivity(), "Screenshot_" + getTime());

Do you have any recommendation how to avoid this crash?
Cheers to all.

2017-04-04 09:32:13 [STRL.testFailed] failed java.lang.RuntimeException: Unable to capture screenshot.
at com.squareup.spoon.Spoon.screenshot(Spoon.java:89)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:62)
at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.loginCarousel(LoginFlow.java:138)
at ccccccccccccccccccccccccccccccccccccccccccccccccccccccccctest1Login(Screenshots.java:195)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at junit.framework.TestResult.runProtected(TestResult.java:133)
at android.support.test.internal.runner.junit3.DelegatingTestResult.runProtected(DelegatingTestResult.java:90)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:49)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:63)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:24)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:270)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1886)
Caused by: java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:829)
at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
at com.squareup.spoon.Spoon.takeScreenshot(Spoon.java:95)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:85)

**Comment by JakeWharton** [comment]
Your activity hasn't run measure or layout yet. I recommend switching to use Espresso which will block until the main thread is clear (and thus measure and layout have run) before executing the screenshot.

**Comment by tir38** [comment]
I know this is already closed but... If you upgrade to 1.7.x you'll see a better explanation via #380
