### ISSUE TITLE
Uiautomator+Spoon 截图，提示：java.lang.RuntimeException: Unable to capture screenshot.

### ISSUE THREAD

**Issue by ismiu** [square/spoon#449]
执行代码如下
public ActivityTestRule<MainActivity> mActivityRule = new ActivityTestRule<>(
        MainActivity.class);
@Test
public void  test_case() throws UiObjectNotFoundException, IOException, InterruptedException {
    ListView_public.Refresh();
    device.pressHome();
    System.out.println("Ui========="+mActivityRule.getActivity());
    Spoon.screenshot(mActivityRule.getActivity(),"test");
    device.pressHome();
}
运行编译后提示：java.lang.RuntimeException: Unable to capture screenshot.
java.lang.RuntimeException: Unable to capture screenshot.
at com.squareup.spoon.Spoon.screenshot(Spoon.java:89)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:62)
at miu.qfdapptest.OneToMany_ForPad.Pad_TestWelcome.test_case(Pad_TestWelcome.java:59)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:69)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
at com.squareup.spoon.Spoon.screenshot(Spoon.java:80)
... 31 more

这是为什么？？？？

**Comment by JakeWharton** [comment]
You passed in `null` instead of an actual `Activity` instance.

**Comment by ismiu** [comment]
The Spoon.screenshot(),must be used in the project source code?

**Comment by ismiu** [comment]
@JakeWharton How can I get an actual Activity instance ?

**Comment by JakeWharton** [comment]
With UI automator? You probably can't. You'll have to wait until Spoon 2.0
comes out and we might have a better means of taking screenshots.

**Comment by ismiu** [comment]
@JakeWharton But why someone can run too ,with Uiautomator.

**Comment by ismiu** [comment]
@JakeWharton If with Espresso,can run??
