### ISSUE TITLE
com.android.ddmlib.InstallException: Connection reset by peer

### ISSUE THREAD

**Issue by lewajiyang** [square/spoon#475]
I am using spoon by jenkins,one device throws this exception.I don't know if it is a known issue.
com.android.ddmlib.InstallException: Connection reset by peer
    at com.android.ddmlib.Device.installPackage(Device.java:886)
    at com.squareup.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:197)
    at com.squareup.spoon.SpoonDeviceRunner.main(SpoonDeviceRunner.java:535)
Caused by: java.io.IOException: Connection reset by peer

**Comment by JakeWharton** [comment]
That indicates the device closed the adb connection. There's nothing Spoon specific about this nor that Spoon itself can do. Reboot the emulator and hope it doesn't happen that often.

**Comment by lewajiyang** [comment]
not often,thousands of times only appeared once.Thanks for your reply.
