### ISSUE TITLE
Spoon crash on Jenkins

### ISSUE THREAD

**Issue by hannesa2** [square/spoon#523]
We see a lot of this in our Jenkins, has someone a clue what's wrong here ?
Any hint is helpful !
```
:app:spoonDebugAndroidTestException in thread "Device List Monitor" java.lang.NullPointerException
	at com.android.ddmlib.EmulatorConsole.checkConnection(EmulatorConsole.java:319)
	at com.android.ddmlib.EmulatorConsole.getConsole(EmulatorConsole.java:233)
	at com.android.ddmlib.DeviceMonitor.queryAvdName(DeviceMonitor.java:246)
	at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:218)
	at com.android.ddmlib.DeviceMonitor.access$400(DeviceMonitor.java:56)
	at com.android.ddmlib.DeviceMonitor$DeviceListUpdateListener.deviceListUpdate(DeviceMonitor.java:658)
	at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.processIncomingDeviceData(DeviceMonitor.java:843)
	at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.run(DeviceMonitor.java:777)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by JakeWharton** [comment]
I'm not sure how Spoon is related here other than invoking ddmlib. I would report the bug to b.android.com/new to make sure they're aware of it.
