### ISSUE TITLE
Spoon runner crash on latest snapshot spoon-runner-2.0.0-20181002.234303-49-all.jar

### ISSUE THREAD

**Issue by tushar-acharya** [square/spoon#550]
Spoon runner crashing with the below log when using the latest jar. There were no errors until the previous version spoon-runner-2.0.0-20180809.153244-48-all.jar

17:49:51 [#2 integration test on Phone] [app-pr-pipeline] Running shell script
17:49:51 [#2 integration test on Phone] + java -jar /root/bin/spoon-runner-2.0.0-jar-with-dependencies.jar app/build/outputs/apk/app-internal-staging-debug-androidTest.apk app/build/outputs/apk/app-internal-staging-debug.apk --serial ea92b3970845:5555 --debug --adb-timeout PT4M --output app/build/spoon/internalStaging/debug --sdk /root/android-sdk-linux -e numShards 20 -e shardIndex 1 -e notAnnotation de.axelspringer.yana.test.filters.Flaky,de.axelspringer.yana.test.filters.AcceptanceTest
17:49:51 [#2 integration test on Phone] Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
17:49:51 [#2 integration test on Phone] 	at com.squareup.spoon.Main.main(main.kt)
17:49:51 [#2 integration test on Phone] Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
17:49:51 [#2 integration test on Phone] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
17:49:51 [#2 integration test on Phone] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
17:49:51 [#2 integration test on Phone] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
17:49:51 [#2 integration test on Phone] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
17:49:51 [#2 integration test on Phone] 	... 1 more

**Comment by edenman** [comment]
Should be fixed by #551, thanks for reporting!

**Comment by 0rzech** [comment]
@edenman Is there any snapshot containing #551 fix available?

**Comment by edenman** [comment]
Timestamps on https://oss.sonatype.org/content/repositories/snapshots/com/squareup/spoon/ seem to be after the fix was merged, so yes.

**Comment by 0rzech** [comment]
The latest version of spoon-runner-all.jar is still 2.0.0-20181002.234303-49.

**Comment by edenman** [comment]
Weird.  Found the error on https://travis-ci.org/square/spoon/builds/448452244
```
* What went wrong:
Execution failed for task ':spoon-runner:uploadArchives'.
> Could not publish configuration 'archives'
   > A POM cannot have multiple artifacts with the same type and classifier. Already have MavenArtifact spoon-runner:zip:zip:null, trying to add MavenArtifact spoon-runner:zip:zip:null.```
